### ISSUE TITLE
Table list is not respected for child/relation lookup

### ISSUE THREAD

**Issue by pyrocks** [schemaspy/schemaspy#968]
I have a postgres v12 DB with partitioned tables.
I want to remove the partitions and show only the parent partitions.
I have extended the DB type pgsql11 to achieve this - this is the new properties file I'm using:
```
extends=pgsql11

# relkind IN ('r','p') --> regular or partitioned \
# NOT relispartition --> not a partition
selectTablesSql=SELECT relname table_name, ns.nspname table_catalog, ns.nspname table_schema, description table_comment, 0 table_rows \
FROM pg_class obj \
INNER JOIN pg_namespace ns ON (obj.relnamespace=ns.oid) \
LEFT JOIN pg_catalog.pg_description ON (objoid=obj.oid AND objsubid =0) \
WHERE nspname = :schema \
AND relkind IN ('r','p') \
AND NOT relispartition
```

## Expected Behavior

Only selected tables by `selectTablesSql` should appear - or in other words I should not be seeing any other table (or partition in this case) not returned by this query in any of the generated pages/diagrams.

## Current Behavior

The table list under the schema indeed lists only the selected tables, however:
1. when clicking on a table `foo` which the partitioned table `bar` has a FK to - it shows `bar` + all of its partitions in the relationships diagram. 
2. Similarly - on the table list, the number of children for `foo` includes the number of partitions. So if `bar` has 3 partitions the count is 4 instead of 1.

## Possible Solution

When looking up for child tables and relations - filter out anything that is not part of the list returned by `selectTablesSql`

## Steps to Reproduce (for bugs)

1. Create a table `foo`, Create a natively partitioned table `bar` with at least one partition that has an FK to `foo`
3. Run schemaspy with the above properties file as `-t`
4. See above

## Context

* Database type (e.g. MySQL): postgresql 12
* Database driver version (is you use a special one): JDBC

## Your Environment

* Version used: 6.1.0
* Environment name and version (e.g. Chrome 39): not relevant
* Operating System and version (e.g. Windows 10): not relevant
* Java version: not relevant

**Comment by pyrocks** [comment]
Update: the diagrams actually contains the "parent" partition table twice - once with the schema and another without (in addition to all the partitions)
so in table `foo`'s diagram it is connected to `bar`, `public.bar`, `public.bar_partition1`, `public.bar_partition2` etc while it should only be connected to `bar`.

Update 2:
I now noticed this strange duplication with/without schema on regular tables regardless of partitioning :/

**Comment by npetzall** [comment]
@pyrocks could you supply a simple sql script to setup a database that can trigger the behaviour.

So that we can reproduce the issue.

**Comment by pyrocks** [comment]
Thanks for the quick response 👍 

I did not test, but this should suffice:
```
CREATE TABLE public.foo (
	id int2 NOT NULL,
	name varchar(15) NOT NULL,
	CONSTRAINT foo_name_uq UNIQUE (name),
	CONSTRAINT foo_pk PRIMARY KEY (id)
);

CREATE TABLE public.bar (
	id int8 NOT NULL GENERATED ALWAYS AS IDENTITY,
	name varchar(15) NOT NULL,
	foo_id int2 NOT NULL,
	created_at timestamptz NOT NULL,
	CONSTRAINT bar_uq UNIQUE (id, created_at),
	CONSTRAINT bar_foo_id_fkey FOREIGN KEY (foo_id) REFERENCES public.foo(id)
)
PARTITION BY RANGE (created_at);

CREATE TABLE public.bar_p2022_04 PARTITION OF public.bar FOR VALUES FROM ('2022-04-01 00:00:00+00') TO ('2022-05-01 00:00:00+00');
CREATE TABLE public.bar_p2022_05 PARTITION OF public.bar FOR VALUES FROM ('2022-05-01 00:00:00+00') TO ('2022-06-01 00:00:00+00');
CREATE TABLE public.bar_p2022_06 PARTITION OF public.bar FOR VALUES FROM ('2022-06-01 00:00:00+00') TO ('2022-07-01 00:00:00+00');
```

**Comment by pyrocks** [comment]
p.s I use `-noimplied -nopages -norows`, the rest is standard. just in case it makes a difference

**Comment by pyrocks** [comment]
@npetzall any update on this?
I changed `ns.nspname table_catalog` to `current_database() table_catalog` in the overwritten query, it didn't help.

**Comment by npetzall** [comment]
Sadly no updates yet, haven't had the time to verify it.
But there is also a filtering that is done using `tableTypes` more on that in #717
Where I also saw an issue with the driver version.

If you could supply the jdbc driver version I'll try to have a look tonight(in 12-13 hours).

I'll see what can be done, this could possibly be resolved with a `-x` or `-X` for diagram
https://schemaspy.readthedocs.io/en/latest/configuration/commandline.html#diagram-related
or `-I` for analysis  
https://schemaspy.readthedocs.io/en/latest/configuration/commandline.html#processing

I'm going to test the exclusions things, but mainly look at the duplication issues.

> When looking up for child tables and relations - filter out anything that is not part of the list returned by selectTablesSql

There currently is no such filtering or condition, this is due to the remote FK functionality. If there exists a FK that reference a table in a different schema, this should be presented. But there might be a missing feature here `--no-remote`.

Or better handling of partitioned tables, if we mark a table as partitioned, one can assume that any relationship to that includes it's partitions, and partitions can be generally excluded #163

**Comment by pyrocks** [comment]
We use JDBC version `42.2.25`

>But there is also a filtering that is done using tableTypes more on that in https://github.com/schemaspy/schemaspy/issues/717

I indeed didn't get the partitioned parents - only the child partitions. I will try and report. It still doesn't help me filter out the child partitions, so perhaps a 3rd type of `PARTITION` is needed which I can exclude from the list.


>this could possibly be resolved with...

I have no intension nor desire to manually exclude tables or columns - that's why I went the path of overriding the database type in the first place

>But there might be a missing feature here --no-remote.

I assume this could work

>Or better handling of partitioned tables

That is obviously the best option - I wouldn't have to customize anything, but maybe as simple as adding a 3rd type in tableTypes as suggested above to control what to include.

**Comment by pyrocks** [comment]
I added `tableTypes=TABLE,PARTITIONED TABLE` to the properties file - it made no difference.

**Comment by npetzall** [comment]
Since you have overridden the standard way of retrieving tables, it won't have an effect.

Normally this information is queried from DatabaseMetaData, in that case the `tableTypes` would be used as a filter.
But when adding `selectTablesSql` DatabaseMetaData won't be queried and as such the filtering won't happen.

So `tableTypes=TABLE,PARTITIONED TABLE` would be a substitute for the `selectTablesSql` or the other way around, depending on how you look at it.

**Comment by pyrocks** [comment]
Nice to know. Either way it won't solve my requirement of including the parent tables and excluding all of the partitions  - which I have hoped to achieve by overriding `selectTablesSql`.

**Comment by npetzall** [comment]
I have somewhat good and weird news.

Use your custom `selectTableSql` and add `-noexportedkeys` as an additional argument.

The "partitions" are added when looking up imported/exported keys. This might work in some instances.

So it works for the example you provided. But I'm gonna look into a feature `--no-remote`, since this will cause only tables returned by the selectTablesSql to be included and no other tables.

**Comment by pyrocks** [comment]
Great news - `-noexportedkeys` fixed everything - partitions are excluded - and no duplicate objects!
I wonder why `-noexportedkeys` is not documented, but would gladly replace it with `--no-remote` once developed.
I'm not sure if you want to develop `--no-remote` as part of this or a different issue - so not closing, but feel free to close.
Thanks a lot for your time and assistance... 👏
